version: "2.3"
services:
  bruno_db:
    image: postgres
    container_name: bruno_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=bruno_db
  bruno_app:
    container_name: bruno_app
    depends_on:
      - bruno_db
    build:
      context: bruno_app
      dockerfile: ./Dockerfile
    command: "npm run dev"
    ports:
      - "9000:9000"
    volumes:
      - ./bruno_app:/usr/server
    environment:
      - DATABASE_URL=postgres://postgres:password@bruno_db/bruno_db
  auth_services:
    container_name: auth_service
    build:
      context: services
      dockerfile: ./Dockerfile
    command: "npm run dev"
    ports:
      - "3000:3000"
    volumes:
      - ./services:/usr/services
